### ISSUE TITLE
Mudfish

### ISSUE THREAD

**Issue by Sparh4wk** [Ash258/scoop-Ash258#101]
Hi, so mudfishvpn can be installed now, but its not possible to run it.
First it needts to be started as admin.. thats not an issue, but then Im getting error about

"MUDEC_00003

No TAP-Win32 Driver found.

TAP-Win32 adapter v9 network device is developed by OpenVPN Technologies, Inc and shipped with a part of Mudfish Cloud VPN."

is it possible to fix it? 
Workaround was installing openvpn or tap adapter manually.

**Comment by Ash258** [comment]
No.
