### ISSUE TITLE
Spotify fails to start after reboot

### ISSUE THREAD

**Issue by lx4r** [Ash258/scoop-Ash258#102]
I installed Spotify using this bucket and it worked fine before I rebooted my PC (started and quit the application multiple times without any issues). After a reboot the Spotify installed is launched when starting Spotify and it gets stuck in this state:

![spotify](https://user-images.githubusercontent.com/1402895/73401323-36a8c780-42eb-11ea-907b-2a5bee95c98d.png)

Neither clicking "Retry" nor "Cancel" changes anything except closing the lower window.

I tried uninstalling (`scoop uninstall spotify`) and reinstalling (`scoop install spotify`) the application multiple times but it always got stuck in that installer after a reboot.

Thanks in advance for the help :).

**Comment by Ash258** [comment]
Yes it is correct.

`https://raw.githubusercontent.com/Ash258/scoop-Ash258/fec8b459a72c7dce91ecb78cedffb80ac753ba7c/bucket/Spotify.json`

**Comment by lx4r** [comment]
@Ash258 Sorry, I don't understand what you mean. Does this bucket only contain the Spotify installer and I was somehow starting that instead of the real application?

**Comment by Ash258** [comment]
No. The current state is just non working draft for extraction.

use the link i provided if you want working one with instaler to appdata
`scoop install https://raw.githubusercontent.com/Ash258/scoop-Ash258/fec8b459a72c7dce91ecb78cedffb80ac753ba7c/bucket/Spotify.json`

**Comment by lx4r** [comment]
@Ash258 Ah, okay, thanks! :)
