### ISSUE TITLE
Adding to the official "Extras" repo

### ISSUE THREAD

**Issue by aj0413** [Ash258/Scoop-Ash258#116]
Hi,

Just wanted to ask about any interest in merging some of your manifests into the [https://github.com/lukesampson/scoop-extras](url) repository.

The game launchers for instance would be nice to have in the extras repo since it already has Steam.

Actually end up using Chocolatey for Uplay and EpicGamesLauncher most of the time, but saw your repo and will be switching to using it for now

**Comment by Ash258** [comment]
...

#92

**Comment by aj0413** [comment]
I noticed that; just didn't want to persume you were still doing so after getting 404s for the few links I tried to go back and check.

Either way, clear whoopsy moment. Should've noticed the issue tracker you alread opened for yourself or tried more of the links.

Really appreciate the work.
