### ISSUE TITLE
pwsh-preview update to 7.1.0-preview.1

### ISSUE THREAD

**Issue by JustinGrote** [Ash258/Scoop-Ash258#121]
Autoupdate should work, this worked fine:
`scoop install pwsh-preview@7.1.0-preview.1`

![image](https://user-images.githubusercontent.com/15258962/77679977-8a810700-6f50-11ea-8bbd-c32cc436e26b.png)

**Comment by Ash258** [comment]
...

I really do not know if you enjoy wasting my time or you just cannot research how the whole scoop eco system works. In all cases stop creating issues when you lack basic knowledge. Best possible stop using my personal bucket in general.

b8baf47f1001d9460d65007b479f907e3ae12189

**Comment by JustinGrote** [comment]
Wow, who pissed in your cornflakes this morning? You could have just said "the CI should detect and autoupdate this automatically, thanks, no need to open an issue on it"

This is the reason people hate developers. Have some civility, you're not the all high ivory tower god of everything.
