### ISSUE TITLE
Add docker shim for WSL?

### ISSUE THREAD

**Issue by AlJohri** [Ash258/Scoop-Ash258#123]
WSL:
```
johria@DESKTOP-KTRH652:/mnt/c/Users/Al$ docker

Command 'docker' not found, but can be installed with:

sudo apt install docker.io
```

related: https://github.com/lukesampson/scoop-extras/issues/3771

**Comment by Ash258** [comment]
As stated in notes inside manifest. The manifest do not register any bin or any shortcuts as it is not normal scoop installation. There is no control over the files and cannot be changed. Docker installation is doing everything (shortcut creation, path pollution, all settings).

If you need bash shim, just create custom bash shim in `$env:SCOOP\shims`, which point to actual file (`C:\Program Files\Docker\??\docker.exe`)

**Comment by AlJohri** [comment]
Thanks, I'm pretty new to scoop. I was under the impression this could be added automatically via a post_install step. Is that not the case?

**Comment by Ash258** [comment]
It could be, but not gonna happen. I am not WSL user, I will never use WSL and I will avoid WSL at all costs in the future. There is no reason that my PERSONAL bucket would do such manipulation.

**Comment by AlJohri** [comment]
Thanks @Ash258! Just asking for my own personal bucket. Appreciate the help. https://github.com/AlJohri/scoop-personal

**Comment by JanPokorny** [comment]
@Ash258 Now I'm just curious, why the strongly negative stance against WSL? I have never met anyone opposing it, so I'm interested in your reasons.
