### ISSUE TITLE
Changing Docker Images Location?

### ISSUE THREAD

**Issue by AlJohri** [Ash258/Scoop-Ash258#124]
Hi, I was wondering why you are suggesting to change the docker images location. What is the default location when installing Docker Toolbox normally? Seems like the JSON doesn't change that default location so it would be the same as if it were installed via point-and-click?

**Comment by Ash258** [comment]
First of all. Why are you talking about toolbox? The docker manifest here is not docker toolbox. It is full `docker desktop` installation.

I suggest it to keep this out of normal storage, which is same for me and my developers setup. The images do not need to be located on high performance SSD raids, they can be located on any storage. SO when you are working with Windows images you do not waste the storage and lifetime of SSDs.

Yes the manifest do not change it. That is the reason why there is that suggestion. I cannot change it from manifest. I do not want change it from manifest. It is just suggestion.

**Comment by AlJohri** [comment]
I said toolbox inadvertently; I also meant the full Docker Desktop installation. Thanks for the clarification, that makes a lot of sense.
