### ISSUE TITLE
Move Appveyor CI to Shovel

### ISSUE THREAD

**Issue by hoilc** [Ash258/Scoop-Ash258#150]
https://github.com/Ash258/Scoop-Ash258/blob/master/Bucket.Tests.ps1#L68

https://github.com/Ash258/Scoop-Ash258/blob/master/.appveyor.yml#L21

**Comment by Ash258** [comment]
Appveyor will be most likely deprecated in favor of Github Actions. The switch of Ci or repo will happen as soon as Shovel is sanitized with the exit code handling and some additional QOL changes required for this.

Mostly after implementation of `verify` command (PR checks in Actions; checker, hashes, install/uninstall/..) so I do not have to reimplement it in every bucket

Ash258/Scoop-GithubActions#64
