### ISSUE TITLE
I think the "icons" folder in the "DrFolder" software should be placed in the "persist" folder.

### ISSUE THREAD

**Issue by jiayaoO3O** [Ash258/scoop-Ash258#17]
If don't do this, when the `DrFolder` is updated, the `current` folder points to the new `icons` folder and the icon will be lost.

**Comment by Ash258** [comment]
What icons are stored there?

**Comment by jiayaoO3O** [comment]
Some of the template icons that come with this software, I will also put my own icons into this folder, so if the software is updated, my icon path will be wrong, because the path pointed to by the current folder is updated.

**Comment by Ash258** [comment]
I will add this. But if they add new icons to this folder they will not be added. (scoop limitation, which will be gone after lukesampson/scoop#3212)
