### ISSUE TITLE
ScummVM@2.2.0: decompress error

### ISSUE THREAD

**Issue by maxsubs** [Ash258/Scoop-Ash258#204]
7zip.log:

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 28609 bytes (28 KiB)

Extracting archive: E:\Soft\Scoop\apps\ScummVM\2.1.2\scummvm-2.1.2-win32-x86_64.zip

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0

**Comment by Ash258** [comment]
Do you really think it is good
