### ISSUE TITLE
I hope this repository can add the software "free download manager"

### ISSUE THREAD

**Issue by jiayaoO3O** [Ash258/scoop-Ash258#21]
[free download manager](https://www.freedownloadmanager.org/) is a very useful download software, I would be very grateful if you can add it to scoop.

**Comment by Ash258** [comment]
Can't.
Free download manager is innosetup based instlaller and when you unpack it, it just do not work.
It need to be installed, which i just do not like.

See https://github.com/Ash258/scoop-Ash258/blob/master/TODO/FDM.json

**Comment by jiayaoO3O** [comment]
Okay,I just can't find a useful download tool that can download BT without installing it.

**Comment by Ash258** [comment]
lukesampson/scoop-extras#2137
lukesampson/scoop-extras#1598
