### ISSUE TITLE
scoop-auto-completion@nightly: download via aria2 failed

### ISSUE THREAD

**Issue by WalleSx** [Ash258/scoop-Ash258#22]
C:\Users\Simon> scoop install scoop-auto-completion
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  This is a nightly version. Downloaded files won't be verified.
Installing 'scoop-auto-completion' (nightly-20190516) [64bit]
Starting download with aria2 ...
Download: [#3c30e4 0B/0B CN:1 DL:0B]
Download: [#3c30e4 0B/0B CN:1 DL:0B]
Download: [#3c30e4 0B/0B CN:1 DL:0B]
Download: [#3c30e4 0B/0B CN:1 DL:0B]
Download: 05/16 09:29:23 [ERROR] CUID#8 - Download aborted. URI=https://raw.githubusercontent.com/liuzijing97/scoop-auto-completion/master/scoop-completion.ps1
Download: Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://raw.githubusercontent.com/liuzijing97/scoop-auto-completion/master/scoop-completion.ps1
Download:   -> [HttpSkipResponseCommand.cc:219] errorCode=3 Resource not found
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 3c30e4|ERR |       0B/s|C:/Users/Simon/scoop/cache/scoop-auto-completion#nightly-20190516#https_raw.githubusercontent.com_liuzijing97_scoop-auto-completion_maste
r_scoop-completion.ps1
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 3) Resource was not found
ERROR https://raw.githubusercontent.com/liuzijing97/scoop-auto-completion/master/scoop-completion.ps1
    referer=https://raw.githubusercontent.com/liuzijing97/scoop-auto-completion/master/
    dir=C:\Users\Simon\scoop\cache
    out=scoop-auto-completion#nightly-20190516#https_raw.githubusercontent.com_liuzijing97_scoop-auto-completion_master_scoop-completion.ps1

ERROR & 'C:\Users\Simon\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\Simon\scoop\cache\scoop-auto-completion.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/
) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-spl
it-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-pr
ocess=10200 --continue

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/Ash258/scoop-Ash258/issues/new?title=scoop-auto-completion%40nightly%3a+download+via+aria2+failed

**Comment by Ash258** [comment]
`scoop-auto-completion` was renamed to `scoop-completion` (follow upstream rename)

- It is still nightly version and will be until developers make proper release process.
- Now it is psmodule. So there is need to add `Import-Module scoop-completion` into your `$PROFILE` if you want to make it automatically
    - Will be as installer.script when i have time to implement
