### ISSUE TITLE
EpicGamesLauncher@nightly: decompress error

### ISSUE THREAD

**Issue by maephisto666** [Ash258/Scoop-Ash258#274]
Not sure why this is happening. 

The only file that is written is `...\apps\EpicGamesLauncher\nightly-20210502\msi.log` whose content is

```
=== Logging started: 5/2/2021  10:41:44 ===
=== Logging stopped: 5/2/2021  10:41:58 ===
```

**Comment by Ash258** [comment]
![image](https://user-images.githubusercontent.com/13260377/116807534-f65e7780-ab33-11eb-947d-588b80103529.png)
