### ISSUE TITLE
potplayer@210428: Hash check failed

### ISSUE THREAD

**Issue by Brawl345** [Ash258/Scoop-Ash258#275]
Hash check failed!
App:         Ash258/potplayer
URL:         https://t1.daumcdn.net/potplayer/PotPlayer/Version/210428/PotPlayerSetup64.exe#/cosi.7z
First bytes: 77 90 144 0 3 0 0 0
Expected:    5a34054e021ae96eed3b4c61b0b95d6eb6448414c3b2a909a24589efddcb2b88
Actual:      8d6399333fa1c7fe8bd90afaf3a849c9bab6473628b31b673b1fee29fbb4f89a

**Comment by Ash258** [comment]
Use extras bucket
