### ISSUE TITLE
PotPlayer@210428: Hash check failed

### ISSUE THREAD

**Issue by bringchucker** [Ash258/Scoop-Ash258#307]
Hash check failed!
App:         Ash258/PotPlayer
URL:         https://t1.daumcdn.net/potplayer/PotPlayer/Version/210428/PotPlayerSetup64.exe#/cosi.7z
First bytes: 77 90 144 0 3 0 0 0
Expected:    28ca1a438725d8c996a2cf84ba81506350cdda6231249208bdcf7ebfe8843141
Actual:      4f93c4f301b27ba0c8b4ce509b5d6c3700c9d1b7747ef83ac21748d51f8457d6

**Comment by Ash258** [comment]
Do not use my version of Potplayer. Use `extras/potplayer`

**Comment by bringchucker** [comment]
Will do, thanks.
