### ISSUE TITLE
goggalaxy@2.0.41.150: Decompress error

### ISSUE THREAD

**Issue by RavenMacDaddy** [Ash258/Scoop-Ash258#315]
Failed to extract files from D:\Backup\Scoop\apps\goggalaxy\2.0.41.150\setup_galaxy_2.0.41.150.exe.

Log:

; Version detected: 6100 (Unicode)
#931 {%ALLUSERSPROFILE}\GOG.com\Galaxy\changelogs\de-DE.html
Reading slice D:\Backup\Scoop\apps\goggalaxy\2.0.41.150\setup_galaxy_2.0.41.150.exe
#932 {%ALLUSERSPROFILE}\GOG.com\Galaxy\changelogs\en-US.html
#933 {%ALLUSERSPROFILE}\GOG.com\Galaxy\changelogs\es-ES.html
#934 {%ALLUSERSPROFILE}\GOG.com\Galaxy\changelogs\es-MX.html
#935 {%ALLUSERSPROFILE}\GOG.com\Galaxy\changelogs\fr-FR.html
#936 {%ALLUSERSPROFILE}\GOG.com\Galaxy\changelogs\it-IT.html
#937 {%ALLUSERSPROFILE}\GOG.com\Galaxy\changelogs\ja-JP.html
#938 {%ALLUSERSPROFILE}\GOG.com\Galaxy\changelogs\ko-KR.html
#939 {%ALLUSERSPROFILE}\GOG.com\Galaxy\changelogs\pl-PL.html
#940 {%ALLUSERSPROFILE}\GOG.com\Galaxy\changelogs\pt-BR.html
#941 {%ALLUSERSPROFILE}\GOG.com\Galaxy\changelogs\pt-PT.html
#942 {%ALLUSERSPROFILE}\GOG.com\Galaxy\changelogs\ru-RU.html
#943 {%ALLUSERSPROFILE}\GOG.com\Galaxy\changelogs\zh-Hans.html
#944 {%ALLUSERSPROFILE}\GOG.com\Galaxy\changelogs\zh-Hant.html
#945 {%ALLUSERSPROFILE}\GOG.com\Galaxy\redists\expat.dll
Error (EFileError) "Access is denied" at address 0047F20D

**Comment by Ash258** [comment]
![image](https://user-images.githubusercontent.com/13260377/130265790-ad79be59-f45d-4ba8-9ff3-8e8b7ddf64e7.png)
