### ISSUE TITLE
texlive manifest

### ISSUE THREAD

**Issue by kmasuyama** [Ash258/scoop-Ash258#42]
I was looking for a bucket with texlive instead of miktex and I came across your repo. It seems you removed the manifest some time ago, were there problems with the installation? It's surprisingly hard to find texlive on scoop despite it being one of the biggest latex distros, so I was wondering if it's particularly difficult to set up.

**Comment by Ash258** [comment]
- Their updates are mess
- It needs to be installed all the time. 
- Installation is huge

Docker approach is better

**Comment by kmasuyama** [comment]
thanks for the info! I'll look into using docker for texlive
