### ISSUE TITLE
WindowsTerminal: Closes automatically after launch

### ISSUE THREAD

**Issue by Velgus** [Ash258/scoop-Ash258#45]
When installed through scoop, WindowsTerminal currently opens an empty window frame (no content in the window's body) when launched, and closes a second later.

The Windows Store version defaults to opening a Powershell tab.

**Comment by Ash258** [comment]
Yeah I know. It is untested version which do not work. 

![A](https://i.imgur.com/6kUFGqW.png)

**Comment by g4cm4n** [comment]
You can make it work with a few manipulations, but not with scoop installation unfortunately. Although I hope this will help @Ash258 bundle it into his wonderful bucket. 
If you don't use Windows Store and want to install updated version of WindowsTerminal (SelfSigned5.6.0 has outdated profile.json schema - so it's really worth it) all you have to do is:

1. scoop uninstall WindowsTerminal or uninstall SelfSigned5.6.0 if neccesary
2. Download latest official pre-release: https://github.com/microsoft/terminal/releases/ and SelfSigned 5.6.0 version: https://justtekno.com/2019/05/download-and-install-windows-terminal/
3. Unpack msixbundle and SelfSigned archive to separate folders.
4. Delete everything but prefered version of CascadiaPackage like CascadiaPackage_0.2.1831.0_x64.msix from official pre-release directory.
5. Copy CascadiaPackage_2019.5.6.0_x86_x64_arm64.cer from SelfSigned dir and rename it to CascadiaPackage_0.2.1831.0_x64.cer, copy the rest of files to pre-release dir: 
Add-AppDevPackage.ps1, Add-AppDevPackage.resources and Dependencies.
6. Install by following instructions from: https://justtekno.com/2019/05/download-and-install-windows-terminal/

**Comment by h404bi** [comment]
FYI:
https://github.com/h404bi/dorado/blob/5d02ad5bbe9f22373345985a6345ab41116acbcb/bucket/windowsterminal.json

**Comment by Ash258** [comment]
@h404bi Yes this will undoubtedly work, but it will not be installed under scoop, which is something I want to avoid on all manifests when possible.

**Comment by Ash258** [comment]
Working in latest version

![A](https://i.imgur.com/8RbNIsw.png)
