### ISSUE TITLE
postinstall app removed quick access

### ISSUE THREAD

**Issue by DessertArbiter** [Ash258/scoop-Ash258#53]
it removed quick access and i cant figure out how to get it back

**Comment by Ash258** [comment]
Yeah that is correct. That is my settings which I want on all of my workstations.

This manifest should not be used by you or anyone else.

**Comment by DessertArbiter** [comment]
nevermind, i was able to turn it back on by setting `HubMode` to `0` under `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer` in the registry
