### ISSUE TITLE
potplayer error hash

### ISSUE THREAD

**Issue by akkuman** [Ash258/scoop-Ash258#73]
Checking hash of PotPlayerSetup64.exe ... ERROR Hash check failed!
App:         Ash258/potplayer
URL:         https://t1.daumcdn.net/potplayer/PotPlayer/Version/20190919_1.7.20538/PotPlayerSetup64.exe#/cosi.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    a88319f4b33c23ae1a94944dd88d832fb45bf9c1708402ec9c52966ec4ee0a2e
Actual:      c54f447ccd217cb07aca6199722054dd0e2ae97b07aa946192cd4e21b3db7b68

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/Ash258/scoop-Ash258/issues/new?title=potplayer%401.7.20538%3a+hash+check+failed

**Comment by Ash258** [comment]
It is not that hard to click on that link and create issue with that prefilled title ....
