### ISSUE TITLE
goggalaxy@2.0.12.48: decompress error

### ISSUE THREAD

**Issue by lx4r** [Ash258/scoop-Ash258#96]
Sorry for creating another issue but I encountered another problem when trying to install GOG Galaxy apart from the now fixed hash problem:

```
λ  scoop install goggalaxy
Installing 'goggalaxy' (2.0.12.48) [64bit]
setup_galaxy_2.0.12.48.exe (227,8 MB) [======================================================================] 100%
Checking hash of setup_galaxy_2.0.12.48.exe ... ok.
Running installer script...
ERROR Exit code was 1!
Failed to extract files from C:\Users\lx4r\scoop\apps\goggalaxy\2.0.12.48\setup_galaxy_2.0.12.48.exe.
Log file:
  ~\scoop\apps\goggalaxy\2.0.12.48\innounp.log
```

The log file looks like this:

```
; Version detected: 5507 (Unicode)
#520 {%ALLUSERSPROFILE}\GOG.com\Galaxy\selfupdate.json
Reading slice C:\Users\lx4r\scoop\apps\goggalaxy\2.0.12.48\setup_galaxy_2.0.12.48.exe
Error (Exception) "MoveFile failed; code 183.%nCannot create a file when that file already exists" at address 0048BFFC
```

Thanks in advance for the help :)

**Comment by Ash258** [comment]
Cannot reproduce. `-y` is used by default, so everything should be overwritten.

Try cleaning cache.

![image](https://user-images.githubusercontent.com/13260377/73202457-63b67800-413b-11ea-8bb5-c134fb715b56.png)

**Comment by lx4r** [comment]
Sorry, I found some files that were left from a previous installation of GOG Galaxy and after removing them the installation worked. Thanks for the help though. :)
